version: '3.7'

services:
  web:
    image: praveenreddy544/docker_django:django_helloworld_app 
    command: python /code/manage.py runserver 0.0.0.0:8009
    volumes:
      - .:/code
    ports:
      - 8009:8009
